// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package deeplink.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class GetAttributeValueByEntityName extends CustomJavaAction<java.lang.String>
{
	private java.lang.String Entity;
	private java.lang.String AttributeName;

	public GetAttributeValueByEntityName(IContext context, java.lang.String Entity, java.lang.String AttributeName)
	{
		super(context);
		this.Entity = Entity;
		this.AttributeName = AttributeName;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetAttributeValueByEntityName";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
